name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        buildType: [ RelWithDebInfo ]
        include:
          - os: windows-latest
            cmake_extra: '-A x64 -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake'
            cmake_generator: '-G "Visual Studio 16 2019"'
    env:
      BuildType: ${{matrix.buildType}}
      BuildDir: ${{github.workspace}}/BLD
      InstallPrefix: ${{github.workspace}}/INSTALL
      PKG_CONFIG_PATH: ${{matrix.pkg_config_path}}
      VCPKG_DEFAULT_TRIPLET: x64-windows

    steps:

      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
          architecture: x64

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel tox flake8

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt install -y cmake libboost-dev libboost-program-options-dev libboost-system-dev libboost-test-dev uuid-dev libnss3-dev libnss3-tools libsasl2-dev sasl2-bin swig python-dev valgrind ruby

      - name: Install Windows dependencies
        if: runner.os == 'Windows'
        run: |
          choco install -y swig --version=4.0.1
# Boost is preinstalled on Windows GHA images, don't bother installing
#          choco install -y boost-msvc-14.1
#          vcpkg install boost-program-options boost-system boost-test
#          vcpkg integrate install

      - name: cmake configure
        run: cmake -S "${{github.workspace}}" -B "${{env.BuildDir}}" "-DCMAKE_BUILD_TYPE=${BuildType}" "-DCMAKE_INSTALL_PREFIX=${InstallPrefix}" ${{matrix.cmake_extra}}
        shell: bash

      - name: cmake build/install
        run: cmake --build "${{env.BuildDir}}" --config ${BuildType} --parallel 3 -t install
        shell: bash

      - id: ctest
        name: ctest
        working-directory: ${{env.BuildDir}}
        run: ctest -C ${BuildType} -V -T Test --no-compress-output ${{matrix.ctest_extra}}
        shell: bash

      - name: Upload Test results
        if: always() && (steps.ctest.outcome == 'failure' || steps.ctest.outcome == 'success')
        uses: actions/upload-artifact@v2
        with:
          name: Test_Results_${{matrix.os}}_${{matrix.buildType}}
          path: ${{env.BuildDir}}/Testing/**/*.xml

      - name: Environment
        if: always()
        run: env -0 | sort -z | tr '\0' '\n'
        shell: bash
